In [1]:
import numpy as np
from IPython.display import display

In [9]:
# 1 
numpy_array = np.arange(1, 17)
display(numpy_array)
display(numpy_array.reshape(4, 4))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
# 2 
ar_array = np.arange(10, 50, 5)
reshaped_array = ar_array.reshape(2, 4)
display(reshaped_array)

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [13]:
# 3
np.random.seed(10)

In [35]:
rand_array = np.random.randint(1, 101, (3, 3))
display('rand_array:', rand_array)
print('max:', rand_array.max())
print('min:', rand_array.min())

'rand_array:'

array([[72, 35, 97],
       [41, 86, 91],
       [27, 84, 17]])

max: 97
min: 17


In [45]:
# 4
np.random.seed(20)

In [65]:
rand_array = np.random.randint(0, 21, 10)
display('rand_array:', rand_array)
display('index:', np.arange(0, 10))

'rand_array:'

array([10, 11,  6, 11, 18,  3, 13, 17, 11, 16])

'index:'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# 4 - 1.
display('rand_array[:5]:', rand_array[:5])

'rand_array[:5]:'

array([10, 11,  6, 11, 18])

In [69]:
# 4 - 2.
display('rand_array[::2]:', rand_array[::2])

'rand_array[::2]:'

array([10,  6, 18, 13, 11])

In [71]:
# 4 - 3.
display('rand_array[::-1]:', rand_array[::-1])

'rand_array[::-1]:'

array([16, 11, 17, 13,  3, 18, 11,  6, 11, 10])

In [79]:
# 5 
arr = np.random.randint(1, 51, (4, 5))
display(arr)
display('arr[2][4]:', arr[2][4])

array([[31, 37,  9, 49, 20],
       [49, 32, 11, 39, 10],
       [24, 33, 13, 15, 32],
       [18, 10, 28, 39, 43]])

'arr[2][4]:'

32

In [81]:
# 6
np.random.seed(30)

In [93]:
ran_array = np.random.randint(0, 101, 15)
display(ran_array)
print('argmax:', ran_array.argmax())
print('argmin:', ran_array.argmin())

array([26, 78, 91, 19, 30, 49, 93, 52, 44, 61, 34, 79, 43, 28, 60])

argmax: 6
argmin: 3


In [99]:
#6 - 1.
ran_array = np.random.randint(0, 101, 15)
np.save('fifteen.npy', ran_array)

ran_array = np.load('fifteen.npy')

In [107]:
# 6 - 2.
display('ran_array % 5:', [(ran_array % 5 == 0)])
display('ran_array % 5', ran_array % 5)

'ran_array % 5:'

[array([False, False, False,  True, False, False,  True,  True, False,
         True, False, False, False, False, False])]

'ran_array % 5'

array([2, 3, 4, 0, 1, 3, 0, 0, 4, 0, 1, 3, 1, 4, 4], dtype=int32)

In [109]:
# 6 - 3.
display(ran_array[(ran_array > 50) | (ran_array < 10)])

array([58,  9, 71, 55, 80])

In [123]:
# Bonus
# ??